language: python

python:
  - 3.9

install:
  - pip install -r requirements.txt
  - pip install black

before_script:
  - python manage.py migrate

script:
  - python manage.py
  - black . --check
  - flake8 --max-line-length=92
